version: '3.8'  # Specify the version of Docker Compose

services:
  exporter:
    build:
      context: .  # Build the Dockerfile in the current directory
      dockerfile: Dockerfile  # Specify the Dockerfile name if it's not the default
    network_mode: host
    privileged: true
    env_file:
      - .env
