version: '3'  # Specify the version of Docker Compose

services:
  exporter:
    build:
      context: .  # Build the Dockerfile in the current directory
      dockerfile: Dockerfile  # Specify the Dockerfile name if it's not the default
    network_mode: host
    privileged: true
    env_file:
      - .env
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000/sd"]
      interval: 30s
      timeout: 10s
      retries: 3
